<?php include('templates/header.php') ?>
<article id="aviso-legal" class="section single">
	<div class="wrapper wrapper--text">
		<header class="section__header">
			<h1 class="section__title">Aviso legal</h1>
		</header>
		<strong style="color:red">Atención. Esta plantilla sirve para cualquier texto legal</strong>
		<div class="section__main">
			<p>VENDEMOS ILUSION, S.L. Registro Mercantil de MADRID, Tomo: 39261 Folio: 70, Sección: 8, Hoja: M 697392 Insc 1ª. C.I.F: B88416425 y Domicilio en AVDA DE LA INSTITUCION LIBRE DE ENSEÑANZA MADRID (MADRID).</p>
			<p>1. Los derechos de propiedad intelectual de la Web www.loterialaveleta.com, su diseño, estructura de navegación, código fuente con códigos de lenguaje HTML, PHP, JavaScript, entre otros, sus bases de datos así como cada uno de los distintos elementos en él contenidos son titularidad de VENDEMOS ILUSION, S.L., a quien corresponde únicamente el ejercicio exclusivo de los derechos de explotación de los mismos en cualquier forma y, en especial, los derechos de reproducción, distribución, comunicación pública y transformación.</p>
			<p>2. Estas condiciones generales regulan el acceso y utilización del sitio Web que VENDEMOS ILUSION, S.L. pone gratuitamente a disposición de los usuarios de Internet. El acceso a dicho sitio implica su aceptación sin reservas. La utilización de determinados servicios ofrecidos en este sitio se regirá además por las condiciones particulares previstas en cada caso, las cuales se entenderán aceptadas por el mero uso de tales servicios.</p>
			<p>3. Los usuarios que accedan a la Web están expresamente autorizados para la visualización de toda la información, la impresión y descarga parcial del contenido sólo y exclusivamente si concurren las siguientes condiciones:</p>
			<p>3.1) Que se realice cuando los elementos reproducidos sean destinados únicamente para uso personal y privado del usuario. Se prohíbe, por tanto, expresamente su utilización con fines comerciales o para su distribución, comunicación pública, transformación o descompilación, incluyendo su envío a través de correo electrónico. También se prohíbe que dichos contenidos sean cedidos o transmitidos a terceros o se instalen en cualquier servidor conectado directa o indirectamente a una red local e Internet, de forma que un grupo de terceros pueda tener acceso a dicha información.</p>
			<p>3.2) Que ninguno de los contenidos relacionados en esta Web sean modificados de manera alguna.</p>
			<p>3.3) Que ningún gráfico, icono o imagen disponible en esta Web sea utilizado, copiado o distribuido separadamente del texto o resto de imágenes que lo acompañan. Cualquier infracción de las prohibiciones y limitaciones contenidas en este apartado, así como en cualquiera de los siguientes- se reputará infracción de los derechos de propiedad intelectual titularidad de VENDEMOS ILUSION, S.L. y dará lugar a las responsabilidades legalmente establecidas al efecto, pudiendo ser perseguida por esta última mediante el ejercicio de las acciones administrativas, civiles o penales que, en su caso, correspondan.</p>
			<h2>Derechos de propiedad intelectual e industrial</h2>
			El Usuario reconoce y acepta que todos los derechos de propiedad industrial e intelectual sobre los contenidos y/o cualesquiera otros elementos insertados en el Sitio Web (incluyendo, a título meramente enunciativo y no limitativo, todos aquellos elementos que conforman la apariencia visual, imagen gráfica y otros estímulos sensoriales de las páginas Web que conforman el sitio Web / "www.loterialaveleta.com", marcas, logotipos, nombres comerciales, textos, críticas y comentarios, imágenes, gráficos, diseños, sonidos, bases de datos, software, diagramas de flujo, presentación, arquitectura de navegación, así como los códigos fuente de las páginas Web pertenecen a VENDEMOS ILUSION, S.L.. y/o a terceros que le han cedido sus derechos. A tales efectos, se entenderá como Sitio Web todas aquellas creaciones incorporadas y expresadas por cualquier medio y/o soporte tangible o intangible, conocido o por conocer, que sea objeto de protección por las disposiciones normativas vigentes en materia de propiedad intelectual e industrial.</p>
			<p>Queda autorizada la mera visualización, impresión, descarga o almacenamiento temporal, ya sea en su totalidad o parcialmente, de los contenidos y/o de los elementos insertados en el Sitio Web o en las páginas que lo conforman exclusivamente para su uso personal, privado y no lucrativo por el usuario siempre que en todo caso se indique el origen y/o autor de los mismos y que, en su caso, aparezca el símbolo del copyright y/o notas de propiedad industrial de sus titulares.</p>
			<p>En ningún caso el acceso al Sitio Web implica ningún tipo de permiso, renuncia, transmisión, licencia o cesión total ni parcial de dichos derechos por parte de sus titulares, salvo que se establezca expresamente lo contrario. Las presentes condiciones de uso del Sitio Web no confieren a los Usuarios ningún otro derecho de utilización, alteración, explotación, reproducción, distribución o comunicación pública del Sitio Web y/o de sus Contenidos distintos de los aquí expresamente previstos. Cualquier otro uso o explotación de cualesquiera derechos estará sujeto a la previa y expresa autorización específicamente otorgada a tal efecto por VENDEMOS ILUSION, S.L. o, en su caso, por el tercero titular de los derechos afectados.</p>
			<p>Queda terminantemente prohibida la utilización de tales elementos, su total o parcial reproducción, comunicación y/o distribución con fines comerciales o lucrativos, así como su modificación, alteración, descompilación y/o cualquier otro acto de explotación del Sitio Web, sus páginas y/o de los contenidos que en ellas se incorporan. Para cualquier otro uso distinto de los expresamente permitidos, será necesario obtener el consentimiento previo por escrito del titular de los derechos de que se trate.</p>
			<h2>Exención de responsabilidad</h2>
			<p>1. VENDEMOS ILUSION, S.L. se reserva la facultad de efectuar siempre que sea necesario y sin necesidad de aviso previo, todas las modificaciones y actualizaciones de la información contenida en su Web, tanto en su versión en español como en otros idiomas-, de la configuración y presentación de éste y de las condiciones de acceso. Los documentos y gráficos publicados en este sitio Web pueden incorporar imprecisiones técnicas o errores tipográficos.</p>
			<p>2. VENDEMOS ILUSION, S.L. proporciona los materiales y gráficos contenidos en este sitio Web sin garantía expresa o implícita de ningún tipo. VENDEMOS ILUSION, S.L. rechaza la existencia de cualquier garantía o condición implícita en la información aquí contenida, incluyendo garantías de viabilidad comercial, de no infracción de la propiedad intelectual o de adecuación a cualquier objetivo específico.</p>
			<p>3. En ningún caso VENDEMOS ILUSION, S.L. o sus proveedores serán responsables de cualquier tipo de daños o perjuicios, incluyendo los derivados de una reducción de beneficios, de la interrupción del negocio o de una pérdida de información debida al uso o mal uso de los materiales contenidos en este servidor, incluso en el caso de que VENDEMOS ILUSION, S.L. haya sido avisada de la posibilidad de tales daños o perjuicios.</p>
			<p>4. VENDEMOS ILUSION, S.L. no garantiza la inexistencia de interrupciones o errores en el acceso a su Web ni en sus diferentes contenidos. Tampoco garantiza que éste se encuentre siempre y en todos los casos actualizados, aunque desarrollará sus mejores esfuerzos para, en su caso, evitarlos, subsanarlos o actualizar dicho contenido lo antes posible. VENDEMOS ILUSION, S.L. no asume ningún tipo de responsabilidad por cualquiera de las informaciones contenidas en otras Web a las que la Web pueda remitir a través de enlaces hipertextuales o “links”.</p>
			<p>5. VENDEMOS ILUSION, S.L. no asume responsabilidad alguna derivada de la concesión o contenidos de los enlaces de terceros a los que se hace referencia en la Web, ni garantiza la ausencia de virus u otros elementos en los mismos que puedan producir alteraciones en el sistema informático (hardware y software), los documentos o los ficheros del usuario, excluyendo cualquier responsabilidad por los daños de cualquier clase causados al usuario por este motivo. Por tanto, no se hace responsable del contenido de ninguno de ellos, ni de los cambios o actualizaciones que puedan experimentar.</p>
			<p>6. Tanto el acceso a este Web como el uso que pueda hacerse de la información contenida en el mismo es de la exclusiva responsabilidad de quien lo realiza. VENDEMOS ILUSION, S.L. no responderá de ninguna consecuencia, daño o perjuicio que pudieran derivarse de dicho acceso o uso de la información. VENDEMOS ILUSION, S.L. no se hace responsable de los posibles errores de seguridad que se puedan producir ni de los posibles daños que puedan causarse al sistema informático del usuario (hardware y software) así como de los ficheros o documentos almacenados en el mismo, como consecuencia de la presencia de virus en el ordenador del usuario utilizado para la conexión a los servicios y contenidos de la Web, de un mal funcionamiento del navegador o del uso de versiones no actualizadas del mismo.</p>
			<p>7. Asimismo VENDEMOS ILUSION, S.L. es titular de los derechos de propiedad industrial referidos a sus productos y servicios, y específicamente de los relativos a la marca registrada. Respecto a las citas de productos y servicios de terceros VENDEMOS ILUSION, S.L. reconoce a favor de sus titulares los correspondientes derechos de propiedad industrial e intelectual, no implicando su sola mención o aparición en el Web la existencia de derechos o responsabilidad alguna de VENDEMOS ILUSION, S.L. sobre los mismos, como tampoco respaldo, patrocinio, recomendación por parte de VENDEMOS ILUSION, S.L..</p>
			<p>8. El uso no autorizado de cualquier información contenida en esta Web, su reventa, así como la lesión de los derechos de Propiedad Intelectual o Industrial de VENDEMOS ILUSION, S.L. dará lugar a las responsabilidades legalmente establecidas.</p>
			<p>9. Cualquier tipo de enlace de terceros a esta Web debe serlo a la página principal o de entrada.</p>
		</div>
	</div>
</article>
<?php include('templates/games.php') ?>
<?php include('templates/footer.php') ?>
